-- ============================================================
-- CatApp — Lista de invitados con códigos únicos (generada del Excel)
-- Pegar en el SQL Editor de Supabase DESPUÉS de schema.sql y ejecutar.
-- Si un código ya existe, esa fila se ignora (no duplica).
-- ============================================================

insert into public.guests (group_name, name, code, adults, kids, under5, total, save_the_date, confirmed, notes)
values
('Familia y amigos', 'NOSOTROS', '4WNA', 2, 2, 0, 4, true, 'pendiente', ''),
('Familia y amigos', 'LILIANA Y JORGE', 'R7CY', 2, 0, 0, 2, true, 'pendiente', ''),
('Familia y amigos', 'JOSE Y FLOR', '8FT5', 2, 1, 1, 4, true, 'pendiente', ''),
('Familia y amigos', 'MAUGE', 'QMSJ', 2, 2, 0, 4, true, 'pendiente', ''),
('Familia y amigos', 'OSVALDO', 'EV3J', 2, 0, 0, 2, true, 'pendiente', ''),
('Familia y amigos', 'PATRI Y NORA', '3TCQ', 2, 0, 0, 2, true, 'pendiente', ''),
('Familia y amigos', 'COCO', 'PDVU', 1, 0, 0, 1, true, 'pendiente', ''),
('Familia y amigos', 'MADE Y CARLOS', 'X49T', 2, 0, 0, 2, true, 'pendiente', ''),
('Familia y amigos', 'LILI Y RUBEN', 'SYWU', 2, 0, 0, 2, true, 'pendiente', ''),
('Familia y amigos', 'MONICA, LULA Y GONZI', '22WM', 3, 0, 0, 3, true, 'pendiente', ''),
('Familia y amigos', 'LORE Y SERGIO', 'RB9Q', 2, 2, 0, 4, true, 'pendiente', ''),
('Grupo Vanesa', 'VANESA', '3X43', 2, 2, 0, 4, true, 'pendiente', ''),
('Grupo Vanesa', 'NADIA', 'FQ89', 2, 1, 0, 3, true, 'pendiente', ''),
('Grupo Vanesa', 'GABY', 'E6VP', 2, 1, 0, 3, true, 'pendiente', ''),
('Grupo Vanesa', 'MAXI', 'AJY8', 2, 1, 0, 3, true, 'pendiente', ''),
('Grupo Mariela', 'MARIELA', '7XBU', 2, 3, 0, 5, false, 'pendiente', ''),
('Grupo Mariela', 'PAO', 'H3VF', 2, 2, 0, 4, false, 'pendiente', 'Ver con cuántos hijos viene'),
('Grupo Mariela', 'ROMIP', 'FA3W', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Mariela', 'VERO', 'NCUG', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Mariela', 'LAQUA', 'Y7SF', 1, 0, 0, 1, false, 'pendiente', ''),
('Grupo Mariela', 'JOSE', 'UYUY', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Mariela', 'JESI', 'YSYY', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Mariela', 'ROMI G', 'F53D', 2, 0, 0, 2, false, 'pendiente', ''),
('Otros adultos', 'MARIA MARTA (médica)', 'Y8N3', 1, 0, 0, 1, true, 'pendiente', ''),
('Otros adultos', 'GABY Y ARIEL', 'V9ZJ', 3, 0, 0, 3, true, 'pendiente', ''),
('Otros adultos', 'LUZ', 'HF6S', 2, 0, 0, 2, true, 'pendiente', ''),
('Otros adultos', 'LUCHI', '4TZY', 1, 0, 0, 1, true, 'pendiente', ''),
('Otros adultos', 'PAO P', '8VMN', 1, 0, 0, 1, true, 'pendiente', ''),
('Otros adultos', 'CHOCHI', 'HZSM', 1, 0, 0, 1, true, 'pendiente', ''),
('Grupo Marote', 'MAROTE', 'UCQC', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'ALDO', 'MH3T', 1, 0, 0, 1, false, 'pendiente', ''),
('Grupo Marote', 'PABLO Y PATRICIA', 'FQAZ', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'JULY', '4MV3', 2, 0, 1, 3, false, 'pendiente', ''),
('Grupo Marote', 'MARICE', 'XS2U', 2, 2, 0, 4, false, 'pendiente', ''),
('Grupo Marote', 'CARO', 'ZRNU', 2, 2, 0, 4, false, 'pendiente', ''),
('Grupo Marote', 'BOLY', 'KEZ6', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'LUCHO', 'B4F2', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'JAVI', 'T9MJ', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'MAPI', '2TAT', 2, 0, 0, 2, false, 'pendiente', ''),
('Grupo Marote', 'ALE', 'X7G4', 2, 2, 0, 4, false, 'pendiente', ''),
('Otros', 'NURIA', '77RM', 2, 2, 0, 4, true, 'pendiente', 'Ver si viene Lucas'),
('Otros', 'MENE', 'WAG3', 2, 2, 0, 4, true, 'pendiente', ''),
('Otros', 'CARLA', 'K5WB', 2, 2, 0, 4, true, 'pendiente', ''),
('Otros', 'MARIANA', '2GQZ', 2, 1, 1, 4, true, 'pendiente', ''),
('Otros', 'MORE Y LUPE', '7TVC', 0, 2, 0, 2, true, 'pendiente', ''),
('Otros', 'SAGAS', 'KCUE', 2, 2, 0, 4, true, 'pendiente', 'Ver si viene Nico'),
('Otros', 'CASSANO', '66PA', 2, 2, 0, 4, true, 'pendiente', 'Ver si viene Salvi'),
('Otros', 'POBLET', 'DMHM', 2, 2, 0, 4, true, 'pendiente', ''),
('Otros', 'CECI B Y ANNIE', 'D2JK', 2, 0, 0, 2, false, 'pendiente', ''),
('Colegio Cata', 'Delfi', 'JBXF', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Lara', 'UZYD', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Cata M', 'DRRY', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Delfi V', 'FJ73', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Oteiza', '9JFW', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Sofi F', '67AN', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Beni', '7DKU', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Agustin E', '645M', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Geronimo', '6S6D', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Joaco Poseiro', 'N8NM', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Valen P', '48NU', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Francisco C', 'BZRB', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Lautaro P', 'XYPU', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Bauti San Martin', 'XN8U', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Cami', 'B5CC', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Sabri', 'EET6', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Pili Landi', 'KWEX', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Isa', 'VWNA', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Agus Natal', 'C6T8', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Esme', '99NY', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Cami Jaime', 'JFRU', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Cami Jung', '5DK2', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Juani Ferrer', 'VZW8', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Martin Rodriguez', '5DVX', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Santi Quintana', 'Y6YK', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Lautaro', '36QP', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Agus Prezioso', 'P9V6', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Tomas Eche', 'PKEP', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Magui Cinca', 'T2QH', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Joaco Cinca', 'U24G', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Iñaki', '22NG', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Leopoldo', 'SBK6', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Joaco Vazquez', 'V3KZ', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Facundo Provera', 'MN2T', 0, 1, 0, 1, true, 'pendiente', ''),
('Colegio Cata', 'Mati Dejulis', 'JYB9', 0, 1, 0, 1, true, 'pendiente', ''),
('Suplentes', 'Chloe', '7C7S', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Sofi Sanchez', 'FM5V', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Juli Gaminera', 'A7DU', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Agus Fassini', 'TYXE', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Juli Alvarez', '7GER', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Guille y Franco', 'VRP6', 0, 2, 0, 2, false, 'pendiente', 'Lista de espera'),
('Suplentes', 'Bruno Bestoso', '7RBZ', 0, 1, 0, 1, false, 'pendiente', 'Lista de espera')
on conflict (code) do nothing;
